# Generated by Django 5.0.4 on 2024-05-07 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=30, verbose_name='Название')),
                ('recipe_description', models.TextField(verbose_name='Описание')),
                ('stages_preparation', models.TextField(verbose_name='Этапы приготовления')),
                ('time_preparation', models.IntegerField(verbose_name='Время приготовления, мин.')),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images', verbose_name='Изображение')),
                ('author', models.CharField(max_length=15, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReciepCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_recipes.categories', verbose_name='Категория')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_recipes.recipes', verbose_name='Рецепт')),
            ],
        ),
    ]
