# Generated by Django 5.0.4 on 2024-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_recipes', '0003_recipes_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReciepCategory',
            new_name='RecipeCategory',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.CharField(max_length=20, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
