# Generated by Django 5.0.4 on 2024-05-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_recipes', '0004_rename_reciepcategory_recipecategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeCategory',
            new_name='RecipeCategoryFilter',
        ),
    ]
